USE ManagementHotel
GO

CREATE TABLE ACCOUNT
(
	ID INT IDENTITY PRIMARY KEY,
	USERNAME VARCHAR(50),
	PASS VARCHAR(50),
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(50),
	SDT INT,
)
GO

CREATE TABLE DICHVU
(
	MADV VARCHAR(50) PRIMARY KEY,
	TENDV NVARCHAR(50),
	DONGIA FLOAT,
	SOLUONG INT,
)
GO

CREATE TABLE USERSA
(
	ID INT IDENTITY PRIMARY KEY,
	MADV VARCHAR(50),
	USERNAME NVARCHAR(100),
	PASS NVARCHAR(50),
	NAME NVARCHAR(50),
	GIOITINH NVARCHAR(15),
	DIACHI NVARCHAR(50),
	EMAIL VARCHAR(50),
	SDT INT,
	TINHTRANG NVARCHAR(100),
	CONSTRAINT fk_ChucVu FOREIGN KEY (MADV) REFERENCES dbo.DICHVU (MADV)
)
GO

CREATE TABLE LOAIPHONG
(
	MALP VARCHAR(50) PRIMARY KEY,
	TENLP NVARCHAR(50),
	TRANGTHIETBI NVARCHAR(100)
)
GO

CREATE TABLE PHONG
(
	MAPHONG VARCHAR(50) PRIMARY KEY,
	MALP VARCHAR(50),
	TENPHONG NVARCHAR(50),
	TINHTRANG NVARCHAR(50),
	GIA FLOAT,
	CONSTRAINT FK_LOAIPHONG FOREIGN KEY (MALP) REFERENCES dbo.LOAIPHONG(MALP)
)
GO

CREATE TABLE PHIEUDATPHONG
(
	MAPDP VARCHAR(50),
	ID INT NOT NULL,
	MAPHONG VARCHAR(50),
	NGAYDEN DATETIME,
	NGAYDI DATETIME,
	TINHTRANG NVARCHAR(50),
	CONSTRAINT fk_Users FOREIGN KEY (ID) REFERENCES dbo.USERSA (ID),
	CONSTRAINT fk_Phong FOREIGN KEY (MAPHONG) REFERENCES dbo.PHONG (MAPHONG)
)
GO

CREATE TABLE HOADON
(
	MAHD VARCHAR(50) PRIMARY KEY,
	ID INT,
	MADV VARCHAR(50),
	NGAYVAO DATETIME,
	NGAYTRA DATETIME,
	TIENPHONG FLOAT,
	TIENDV FLOAT,
	TONGTIEN FLOAT,
	TINHTRANG VARCHAR(50),
	CONSTRAINT fk_Users FOREIGN KEY (ID) REFERENCES dbo.USERSA,
	CONSTRAINT fk_DichVu FOREIGN KEY (MADV) REFERENCES dbo.DICHVU (MADV)
)
GO







